# Generated by Terragrunt from autoinclude block. Do not edit manually.
dependency "vpc" {
  config_path = "../vpc"
  mock_outputs = {
    subnet_ids = ["subnet-a", "subnet-b"]
    vpc_id     = "vpc-mock-123"
  }
  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

inputs = {
  vpc_id     = dependency.vpc.outputs.vpc_id
  subnet_ids = dependency.vpc.outputs.subnet_ids
}
