package com.github.terrapaw.terragrunt.inspection;

import com.github.terrapaw.terragrunt.lang.psi.TerragruntAttribute;
import com.github.terrapaw.terragrunt.lang.psi.TerragruntBlock;
import com.github.terrapaw.terragrunt.lang.psi.TerragruntFunctionCall;
import com.github.terrapaw.terragrunt.lang.psi.TerragruntStringLit;
import com.intellij.codeInspection.*;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.psi.PsiElement;
import com.intellij.psi.PsiElementVisitor;
import com.intellij.psi.PsiFile;
import com.intellij.psi.util.PsiTreeUtil;
import org.jetbrains.annotations.NotNull;

import java.io.File;
import java.util.Set;

public class TerragruntUnresolvedPathInspection extends TerragruntBaseInspection {
    private static final Set<String> PATH_ATTRS = Set.of("config_path", "path");

    /**
     * Checks if a missing path would be generated by terragrunt stack generate.
     * Looks for .terragrunt-stack in the path, finds the parent terragrunt.stack.hcl,
     * and checks if a unit with a matching path attribute is defined.
     */
    private static boolean wouldBeGeneratedByStack(String path, VirtualFile sourceDir) {
        // Normalize the path to find .terragrunt-stack
        String normalized = path.replace("\\", "/");
        if (normalized.startsWith("./")) normalized = normalized.substring(2);
        int stackIdx = normalized.indexOf(".terragrunt-stack/");
        if (stackIdx < 0 && normalized.equals(".terragrunt-stack")) return true;
        if (stackIdx < 0) return false;

        // Extract the unit path (everything after .terragrunt-stack/)
        String afterStack = normalized.substring(stackIdx + ".terragrunt-stack/".length());
        if (afterStack.endsWith("/")) afterStack = afterStack.substring(0, afterStack.length() - 1);
        if (afterStack.isEmpty()) return true;

        // Navigate up from sourceDir to find terragrunt.stack.hcl
        VirtualFile dir = sourceDir;
        for (int i = 0; i < stackIdx; i++) {
            if (normalized.charAt(i) == '/') {
                // skip — we handle relative paths from sourceDir
            }
        }
        // For relative paths with ../, navigate up
        String prefix = stackIdx > 0 ? normalized.substring(0, stackIdx) : "";
        VirtualFile stackParent = sourceDir;
        for (String part : prefix.split("/")) {
            if (part.isEmpty() || part.equals(".")) continue;
            if (part.equals("..")) {
                stackParent = stackParent.getParent();
            } else {
                VirtualFile child = stackParent.findChild(part);
                if (child != null) stackParent = child;
            }
            if (stackParent == null) return false;
        }

        VirtualFile stackFile = stackParent.findChild("terragrunt.stack.hcl");
        if (stackFile == null) return false;

        // Check if the stack file defines a unit with matching path
        try {
            String content = new String(stackFile.contentsToByteArray());
            return content.contains("\"" + afterStack + "\"");
        } catch (Exception e) {
            return false;
        }
    }

    @NotNull
    @Override
    public PsiElementVisitor buildVisitor(@NotNull ProblemsHolder holder, boolean isOnTheFly) {
        return new PsiElementVisitor() {
            @Override
            public void visitElement(@NotNull PsiElement element) {
                if (!(element instanceof TerragruntAttribute attr)) return;
                PsiElement nameElement = attr.getFirstChild();
                if (nameElement == null) return;
                String attrName = nameElement.getText();
                if (!PATH_ATTRS.contains(attrName)) return;

                // Check parent block type
                TerragruntBlock block = PsiTreeUtil.getParentOfType(attr, TerragruntBlock.class);
                if (block == null) return;
                String blockType = block.getFirstChild() != null ? block.getFirstChild().getText() : "";
                if (!blockType.equals("include") && !blockType.equals("dependency")) return;

                // Try to find string literal value (skip if it contains function calls)
                TerragruntStringLit stringLit = PsiTreeUtil.findChildOfType(attr, TerragruntStringLit.class);
                TerragruntFunctionCall funcCall = PsiTreeUtil.findChildOfType(attr, TerragruntFunctionCall.class);
                if (funcCall != null) return; // Can't statically resolve function calls
                if (stringLit == null) return;

                String path = stringLit.getText();
                if (path.length() < 3) return;
                path = path.substring(1, path.length() - 1); // strip quotes
                if (path.contains("${")) return; // skip interpolated strings

                // Resolve relative path
                PsiFile file = attr.getContainingFile();
                VirtualFile vFile = file.getVirtualFile();
                if (vFile == null) return;
                File baseDir = new File(vFile.getParent().getPath());
                File target = new File(baseDir, path);

                if (blockType.equals("dependency")) {
                    // dependency config_path points to a directory
                    File tgFile = new File(target, "terragrunt.hcl");
                    if (!target.isDirectory() && !tgFile.exists()) {
                        // Suppress if path is under .terragrunt-stack and a stack would generate it
                        if (wouldBeGeneratedByStack(path, vFile.getParent())) return;
                        holder.registerProblem(stringLit,
                                "Cannot resolve path '" + path + "'",
                                ProblemHighlightType.GENERIC_ERROR_OR_WARNING);
                    }
                } else {
                    // include path points to a file
                    if (!target.exists()) {
                        holder.registerProblem(stringLit,
                                "Cannot resolve file '" + path + "'",
                                ProblemHighlightType.GENERIC_ERROR_OR_WARNING);
                    }
                }
            }
        };
    }
}
